services:
  Diary.api:
    image: diary.api
    build:
      context: .
      dockerfile: Diary.Api/Dockerfile
  
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynw
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw
  
  elastic_search:
    container_name: els
    image: elasticsearch:8.15.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elk
  
  kibana:
    container_name: kibana
    image: kibana:8.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elastic_search
    environment:
      - ELASTICSEARCH_HOSTS=http://els:9200
      - XPACK_SECURITY_ENABLED=false
    networks:
      - elk
  
  logstash:
    container_name: logstash
    image: logstash:8.15.0
    ports:
      - "5046:5046"
      - "5000:5000/tcp"
      - "5000:5000/udp"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./Diary.Api/logs:/logs
      - ./sincedb:/var/lib/logstash/sincedb
    depends_on:
      - elastic_search
    networks:
      - elk

networks:
  mynw:
  elk:
    driver: bridge
volumes:
  elasticsearch-data: